
Dotpulse:
  NamingConvention:
    Title:
      dividerPage: ' - '
      dividerSite: ' • '
      positionSite: end
      showPath: asc
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Dotpulse.NamingConvention:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Dotpulse.NamingConvention: true
